version: "3.8"

services:
  ecommercenext:
    image: registry.gitlab.com/repository.host/afya_bora:frontend-latest
    environment:
      - NEXT_PUBLIC_STRIPE_KEY=$NEXT_PUBLIC_STRIPE_KEY
      - NEXT_PUBLIC_PER_PAGE=$NEXT_PUBLIC_PER_PAGE
      - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=cloud-public
        - traefik.http.routers.afya_bora_client.entrypoints=websecure
        - traefik.http.routers.afya_bora_client.rule=Host(`${FRONTEND_DOMAIN}`)
        - traefik.http.routers.afya_bora_client.tls=true
        - traefik.http.routers.afya_bora_client.tls.options=default
        - traefik.http.routers.afya_bora_client.tls.certresolver=letsencrypt
        - traefik.http.routers.afya_bora_client.middlewares=traefik-ratelimit,traefik-inflightreq
        - traefik.http.services.afya_bora_client.loadbalancer.server.port=7777
    networks:
      - cloud-public

networks:
  cloud-public:
    external: true
